fix the element placement

diff --git a/elements/rackspace/post-install.d/02-network-manager b/elements/rackspace/post-install.d/02-network-manager
--- a/elements/rackspace/post-install.d/02-network-manager
+++ b/elements/rackspace/post-install.d/02-network-manager
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+# Enable debugging mode based on a condition
+if [ 0 -gt 0 ]; then
+    set -x
+else
+    set -v
+fi
+
+# Ensure the script exits on error
+set -eu
+set -o pipefail
+
 isRH=0
 
 egrep -q -i 'Centos|RedHat' /etc/redhat-release 2>/dev/null && isRH=1
diff --git a/elements/rackspace/post-install.d/10-add-custom-scripts b/elements/rackspace/post-install.d/10-add-custom-scripts
--- a/elements/rackspace/post-install.d/10-add-custom-scripts
+++ b/elements/rackspace/post-install.d/10-add-custom-scripts
@@ -1,5 +1,15 @@
 #!/bin/bash
-set -eux
+
+# Enable debugging mode based on a condition
+if [ 0 -gt 0 ]; then
+    set -x
+else
+    set -v
+fi
+
+# Ensure the script exits on error
+set -eu
+set -o pipefail
 
 echo "Adding a script to run 'lsblk' upon user login"
 
diff --git a/elements/rackspace/post-install.d/90-clean-tasks b/elements/rackspace/post-install.d/90-clean-tasks
--- a/elements/rackspace/post-install.d/90-clean-tasks
+++ b/elements/rackspace/post-install.d/90-clean-tasks
@@ -1,6 +1,15 @@
 #!/bin/bash
 
-set -eux  # Enable debugging and exit on error
+# Enable debugging mode based on a condition
+if [ 0 -gt 0 ]; then
+    set -x
+else
+    set -v
+fi
+
+# Ensure the script exits on error
+set -eu
+set -o pipefail
 
 echo "Create ipa-rescue-config directory and file"
 mkdir /etc/ipa-rescue-config
